# This is a basic workflow to help you get started with Actions

name: Recompile

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: download
        run: |
              wget https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.tar.gz
              tar -xf boost_1_79_0.tar.gz
              
      - name: compile
        run: |
              cd boost_1_79_0
              ./bootstrap.sh --prefix=../boost_lib/
              ./b2 install
              cd ..
              
      - name: zip
        run: |
              tar -czf boost.tar.gz boost_lib
      
      - name: delete artifacts
        run: |
              rm boost_1_79_0.tar.gz
              rm -r boost_1_79_0
              rm -r boost_lib
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Actinos compile

